### ISSUE TITLE
EBS policy not deleting the EBS volume after it is marked for operation. 

### ISSUE THREAD

**Issue by KeerthigaKrishnan** [jimrazmus/c7n-policies#10]
I had used the policy of ebs unattached and added tag and marked for operation of 1 day duration. 

But the policy of deleting the marked ebs is not deleting. I used the same policy.

**Comment by jimrazmus** [comment]
What is the value of the "c7n_ebs_volume_delete_unattached" tag on the volume?

For example, here is the value on a volume that was recently deleted for me:  "Resource does not meet policy: delete@2018/08/14"

**Comment by jimrazmus** [comment]
Closing this issue due to lack of response to the request for more information.
